name: SUB-ETHA-TINYCOMMS

on: push

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    container: docker://mattprompt/sub-etha-tinycomms:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          cd test
          make all
